name: Trigger AzDO PR pipeline

on:
  workflow_dispatch:
  pull_request:


jobs:
  trigger-azdo-tests:
    runs-on: ubuntu-latest
    environment: ni-dev
    steps:
      - name: Set variables for PR run
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "BUILD_REF=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          echo "REPO_URL=${{ github.server_url }}/${{ github.event.pull_request.head.repo.full_name }}.git" >> $GITHUB_ENV
          echo "____________________________________"
          echo "MERGE_PR=true" >> $GITHUB_ENV
          echo "BASE_REPO_URL=${{ github.server_url }}/${{ github.repository }}.git" >> $GITHUB_ENV
          echo "BASE_REF=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
          echo "HEAD_REPO_URL=${{ github.server_url }}/${{ github.event.pull_request.head.repo.full_name }}.git" >> $GITHUB_ENV
          echo "HEAD_REF=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          echo "HEAD_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
      - name: Set variables for manual run
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "BUILD_REF=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "REPO_URL=${{ github.server_url }}/${{ github.repository }}.git" >> $GITHUB_ENV
          echo "____________________________________"
          echo "MERGE_PR=false" >> $GITHUB_ENV
          echo "BASE_REPO_URL=${{ github.server_url }}/${{ github.repository }}.git" >> $GITHUB_ENV
          echo "BASE_REF=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "HEAD_REPO_URL=" >> $GITHUB_ENV
          echo "HEAD_REF=" >> $GITHUB_ENV
          echo "HEAD_SHA=" >> $GITHUB_ENV

